# Generated by Django 4.0.6 on 2022-08-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
